name: Build Windows Exe

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Baixar código
              uses: actions/checkout@v4

            - name: Configurar Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Instalar dependências Python
              run: |
                  python -m pip install --upgrade pip
                  pip install pillow pillow-heif piexif customtkinter pyinstaller

            - name: Baixar FFprobe e Organizar na pasta bin
              shell: cmd
              run: |
                  mkdir bin
                  curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
                  7z e ffmpeg.zip */bin/ffprobe.exe -obin -r

            - name: Criar Executável (Build)
              # --add-binary "origem;destino"
              # Pegamos de bin/ffprobe.exe (do projeto) e colocamos em bin/ (dentro do exe)
              run: |
                  pyinstaller --noconfirm --onefile --windowed --icon="app_icon.ico" --collect-all customtkinter --add-binary "bin/ffprobe.exe;bin" main.pyw

            - name: Upload do Executável
              uses: actions/upload-artifact@v4
              with:
                  name: Organize photos
                  path: dist/*.exe
